#pragma config(Sensor, S1,     Sensor1,        sensorEV3_Ultrasonic)
#pragma config(Sensor, S4,     Sensor4,        sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          beltA,         tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, PIDControl, driveRight, encoder)
#pragma config(Motor,  motorD,          beltD,         tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//Configuration - Change these to fine tune.
	int drivingSpeed = 15;
	int drivingDuration = 2000;
/*
	int gripperRange = 5;
	int correctionRange = 8;
	int errorMargin = 2;
	int gripperSpeed = 50;
	//int gripperDuration = 500; //ms


	//Variables
	int currentDistance = 0;
	bool gripperOpen = true;
	bool delivered = false;
	bool correcting = false;
	int correctionDuration = 0;
*/

//Stop driving
void stopMoving()
{

	setMotorSpeed(leftMotor, 0);
	setMotorSpeed(rightMotor, 0);
}

//Moves Forward
void moveForward()
{
	setMotorSpeed(leftMotor, drivingSpeed);		//Set the leftMotor (motor1) to half power (50)
	setMotorSpeed(rightMotor, drivingSpeed);  //Set the rightMotor (motor6) to half power (50)
}

//Overload - for a duration
void moveForward(int duration)
{
	moveForward();
	sleep(duration);
	stopMoving();
}

//Moves Backwards
void moveBackward()
{
	setMotorSpeed(leftMotor, -drivingSpeed);		//Set the leftMotor (motor1) to half power (50)
	setMotorSpeed(rightMotor, -drivingSpeed);  //Set the rightMotor (motor6) to half power (50)
}

//Overload - for a duration
void moveBackward(int duration)
{
	moveBackward();
	sleep(duration);
	stopMoving();
}

task main()
{
	//Infinite Loop
	while(true)
	{
		moveForward(drivingDuration);
		//playSound(soundBeepBeep);
    moveBackward(drivingDuration);
    //playSound(soundBlip);
	}


}
