#pragma config(Sensor, S1,     colorSensor,    sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S4,     sonarSensor,    sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          gripperMotor,  tmotorEV3_Medium, PIDControl, encoder)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int gripperRange = 5;
int correctionRange = 8;
int errorMargin = 2;
int gripperSpeed = 50;
int drivingSpeed = 25;
int drivingDuration = 2500;

//Variables
int currentDistance = 0;
bool gripperOpen = true;
bool delivered = false;
bool correcting = false;
int correctionDuration = 0;

void stopMove()
{
	setMotorSpeed(leftMotor, 0);
	setMotorSpeed(rightMotor, 0);
}

void forwardMove()
{
	setMotorSpeed(leftMotor, drivingSpeed);
	setMotorSpeed(rightMotor, drivingSpeed);	
}

void forwardMove(int duration)
{
	forwardMove();
	sleep(duration);
	stopMove();
}

void backwardMove()
{
	setMotorSpeed(leftMotor, -drivingSpeed);
	setMotorSpeed(rightMotor, -drivingSpeed);
}

void backwardMove(int duration)
{
	backwardMove();
	sleep(duration);
	stopMove();
}

void closeGripper()
{
	resetMotorEncoder(gripperMotor);
	setMotorSpeed(gripperMotor, -gripperSpeed);
	while (getMotorEncoder(gripperMotor) > -1500) {}
	setMotorSpeed(gripperMotor, 0);
}

void openGripper()
{
	resetMotorEncoder(gripperMotor);
	setMotorSpeed(gripperMotor, gripperSpeed);
	while (getMotorEncoder(gripperMotor) < 1500) {}
	setMotorSpeed(gripperMotor, 0);
}

task main()
{
	//Infinite Loop
	while(true)
	{
		// Read the sensor
		currentDistance = getUSDistance(sonarSensor);

		//Has payload not been delivered
		if(!delivered)
		{
			//Is payload not being carried
			if (gripperOpen)
			{

				//Is payload in gripper range, grab it.
				if((gripperRange - currentDistance) > 0)
				{
					if (correcting)
					{
						correctionDuration = time1[T1];
						correcting = false;
					}
				
					//Stop driving
					stopMove();

					//Close Gripper
					closeGripper();
					gripperOpen = false;
				}
				
				//Is payload there, but out of range of claws, drive forward
				else if ((gripperRange - currentDistance) > -correctionRange)
				{
					if(!correcting)
					{
						//set timer to zero
						clearTimer(T1); 
						correcting = true;
					}
		
					//moves forward a little
					forwardMove();
				}
			}
			
			//are grippers closed but payload not delivered
			else
			{
				//drive to location
				forwardMove(drivingDuration);
				
				//Open gripper to drop off payload
				openGripper();

				//setMotorSpeed(gripperMotor, -gripperSpeed);
				//sleep(gripperDuration);
				gripperOpen = true;
				delivered = true;
			}
			if(currentDistance > (gripperRange+correctionRange+errorMargin))
			{
				stopMove();
			}
		}
//Is payload delivered
		else
		{
			//return to carrier
			backwardMove(drivingDuration);

			//reverse any corrections made
			backwardMove(correctionDuration);
			
			//For next loop to start
			delivered = false;
		}
	}
}
