#pragma config(Sensor, S1,     touchSensor,    sensorNone)
#pragma config(Sensor, S2,     gyroSensor,     sensorNone)
#pragma config(Sensor, S3,     colorSensor,    sensorNone)
#pragma config(Sensor, S4,     sonarSensor,    sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          gripperMotor,  tmotorEV3_Medium, PIDControl, encoder)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, PIDControl, driveRight, encoder)
#pragma config(Motor,  motorD,           ,             tmotorEV3_Large, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*------------------------------------------------------------------------------------------------
  This program will ..................

                            ROBOT CONFIGURATION: LEGO EV3 REM Bot
    MOTORS & SENSORS:
    [I/O Port]          [Name]              [Type]                			[Location]
    motorA							gripperMotor				Lego EV3 motor					Centre Front.
    MotorC        			leftMotor           LEGO EV3 Motor		      Left side motor
    MotorB       				rightMotor          LEGO EV3 Motor		      Right side motor (reversed)
    Sensor4       			sonarSensor         LEGO EV3 Ultrasonic		  Under Gripper (front/centre)
------------------------------------------------------------------------------------------------*/

task main()
{
	//Configuration - Change these to fine tune.
	int gripperRange = 4;
	int correctionRange = 8;
	int errorMargin = 2;
	int gripperSpeed = 50;
	//int gripperDuration = 500; //ms
	int drivingSpeed = 25;
	int drivingDuration = 2500;

	//Variables
	int currentDistance = 0;
	bool gripperOpen = true;
	bool delivered = false;
	int correctionTraveled = 0;

//Infinite Loop
	while(true)
	{
		// Read the sensor
		currentDistance = getUSDistance(sonarSensor);

//Has payload not been delivered
		if(!delivered)
		{
//Is payload not being carried
			if (gripperOpen)
			{

//Is payload in gripper range, grab it.
				if((gripperRange - currentDistance) > 0)
				{
					//Stop driving
					setMotorSpeed(leftMotor, 0);
					setMotorSpeed(rightMotor, 0);

					//Close Gripper
					resetMotorEncoder(gripperMotor);
					setMotorSpeed(gripperMotor, -gripperSpeed);
					while (getMotorEncoder(gripperMotor) > -1500) {}
					setMotorSpeed(gripperMotor, 0);
					gripperOpen = false;
				}
//Is payload there, but out of range of claws, drive forward
				else if ((gripperRange - currentDistance) > -correctionRange)
				{
					//moves forward a little
					setMotorSpeed(leftMotor, (drivingSpeed/2));
					setMotorSpeed(rightMotor, (drivingSpeed/2));
				}
			}
//are grippers closed but payload not delivered
			else
			{
				//drive to location
				setMotorSpeed(leftMotor, drivingSpeed);		//Set the leftMotor (motor1) to half power (50)
				setMotorSpeed(rightMotor, drivingSpeed);  //Set the rightMotor (motor6) to half power (50)
				sleep(drivingDuration);										//Wait for x milliseconds before continuing on in the program.

				//Stop driving
				setMotorSpeed(leftMotor, 0);
				setMotorSpeed(rightMotor, 0);

				//Open gripper to drop off payload
				resetMotorEncoder(gripperMotor);
				setMotorSpeed(gripperMotor, gripperSpeed);
				while (getMotorEncoder(gripperMotor) < 1500) {}
				setMotorSpeed(gripperMotor, 0);

				//setMotorSpeed(gripperMotor, -gripperSpeed);
				//sleep(gripperDuration);
				gripperOpen = true;
				delivered = true;
			}
			if(currentDistance > (gripperRange+correctionRange+errorMargin))
			{
				setMotorSpeed(leftMotor, 0);
				setMotorSpeed(rightMotor, 0);
			}
		}
//Is payload delivered
		else
		{
			//return to carrier
			setMotorSpeed(leftMotor, -drivingSpeed);		//Set the leftMotor (motor1) to half power (50)
			setMotorSpeed(rightMotor, -drivingSpeed);  	//Set the rightMotor (motor6) to half power (50)
			sleep(drivingDuration);																//Wait for x milliseconds before continuing on in the program.

			//For next loop to start
			delivered = false;
		}
	}
}
